player.say("placing bedrock")
blocks.place(BEDROCK,  pos(0,0,1))
blocks.place(BEDROCK, pos(0,0,2))
blocks.place(BEDROCK, pos(0,0,3))
blocks.place(BEDROCK, pos(0,0,4))
blocks.place(BEDROCK, pos(0,0,5))
blocks.place(BEDROCK, pos(0,0,6))
//what   action  type   l/r  u/d f/b

//bottom
blocks.place(BEDROCK, pos(-5,0,1))
blocks.place(BEDROCK, pos(-4,0,1))
blocks.place(BEDROCK, pos(-3,0,1))
blocks.place(BEDROCK, pos(-2,0,1))
blocks.place(BEDROCK, pos(-1,0,1))
//length
blocks.place(BEDROCK, pos(0,1,1))
blocks.place(BEDROCK, pos(0,2,1))
blocks.place(BEDROCK, pos(0,3,1))
blocks.place(BEDROCK, pos(0,4,1))
blocks.place(BEDROCK, pos(0,5,1))
//wall
blocks.place(BEDROCK, pos(-5,1,1))
blocks.place(BEDROCK, pos(-4,1,1))
blocks.place(BEDROCK, pos(-3,1,1))
blocks.place(BEDROCK, pos(-2,1,1))
blocks.place(BEDROCK, pos(-1,1,1))
//wall2
blocks.place(BEDROCK, pos(-5,2,1))
blocks.place(BEDROCK, pos(-4,2,1))
blocks.place(BEDROCK, pos(-3,2,1))
blocks.place(BEDROCK, pos(-2,2,1))
blocks.place(BEDROCK, pos(-1,2,1))
//wall3
blocks.place(BEDROCK, pos(-5,3,1))
blocks.place(BEDROCK, pos(-4,3,1))
blocks.place(BEDROCK, pos(-3,3,1))
blocks.place(BEDROCK, pos(-2,3,1))
blocks.place(BEDROCK, pos(-1,3,1))
//wall4 
blocks.place(BEDROCK, pos(-5,4,1))
blocks.place(BEDROCK, pos(-4,4,1))
blocks.place(BEDROCK, pos(-3,4,1))
blocks.place(BEDROCK, pos(-2,4,1))
blocks.place(BEDROCK, pos(-1,4,1))
//wall 5
blocks.place(BEDROCK, pos(-5,5,1))
blocks.place(BEDROCK, pos(-4,5,1))
blocks.place(BEDROCK, pos(-3,5,1))
blocks.place(BEDROCK, pos(-2,5,1))
blocks.place(BEDROCK, pos(-1,5,1))
//wall length
blocks.place(BEDROCK,  pos(-1,0,2))
blocks.place(BEDROCK, pos(-2,0,2))
blocks.place(BEDROCK, pos(-3,0,2))
blocks.place(BEDROCK, pos(-4,0,2))
blocks.place(BEDROCK, pos(-5,0,2))
//floor1
blocks.place(BEDROCK,  pos(-1,0,3))
blocks.place(BEDROCK, pos(-2,0,3))
blocks.place(BEDROCK, pos(-3,0,3))
blocks.place(BEDROCK, pos(-4,0,3))
blocks.place(BEDROCK, pos(-5,0,3))
//floor2
blocks.place(BEDROCK,  pos(-1,0,4))
blocks.place(BEDROCK, pos(-2,0,4))
blocks.place(BEDROCK, pos(-3,0,4))
blocks.place(BEDROCK, pos(-4,0,4))
blocks.place(BEDROCK, pos(-5,0,4))
//floor3
blocks.place(BEDROCK,  pos(-1,0,5))
blocks.place(BEDROCK, pos(-2,0,5))
blocks.place(BEDROCK, pos(-3,0,5))
blocks.place(BEDROCK, pos(-4,0,5))
blocks.place(BEDROCK, pos(-5,0,5))
//floor4
blocks.place(BEDROCK,  pos(-1,0,6))
blocks.place(BEDROCK, pos(-2,0,6))
blocks.place(BEDROCK, pos(-3,0,6))
blocks.place(BEDROCK, pos(-4,0,6))
blocks.place(BEDROCK, pos(-5,0,6))
//wall length
blocks.place(BEDROCK, pos(-5,5,2))
blocks.place(BEDROCK, pos(-4,5,2))
blocks.place(BEDROCK, pos(-3,5,2))
blocks.place(BEDROCK, pos(-2,5,2))
blocks.place(BEDROCK, pos(-1,5,2))
blocks.place(BEDROCK,pos(-0,5,2))
//wall lenthg 3
blocks.place(BEDROCK, pos(-5,5,4))
blocks.place(BEDROCK, pos(-4,5,4))
blocks.place(BEDROCK, pos(-3,5,4))
blocks.place(BEDROCK, pos(-2,5,4))
blocks.place(BEDROCK, pos(-1,5,4))
blocks.place(BEDROCK, pos(-0,5,4))
//wall lenghth 4
blocks.place(BEDROCK, pos(-5,5,5))
blocks.place(BEDROCK, pos(-4,5,5))
blocks.place(BEDROCK, pos(-3,5,5))
blocks.place(BEDROCK, pos(-2,5,5))
blocks.place(BEDROCK, pos(-1,5,5))
blocks.place(BEDROCK, pos(-0,5,5))
//wall lenghth 5
blocks.place(BEDROCK, pos(-5,5,6))
blocks.place(BEDROCK, pos(-4,5,6))
blocks.place(BEDROCK, pos(-3,5,6))
blocks.place(BEDROCK, pos(-2,5,6))
blocks.place(BEDROCK, pos(-1,5,6))
blocks.place(BEDROCK, pos(-0,5,6))

blocks.place(BEDROCK, pos(-5,5,3))
blocks.place(BEDROCK, pos(-4,5,3))
blocks.place(BEDROCK, pos(-3,5,3))
blocks.place(BEDROCK, pos(-2,5,3))
blocks.place(BEDROCK, pos(-1,5,3))
blocks.place(BEDROCK,pos(-0,5,3))
//wall 2 
blocks.place(BEDROCK,  pos(-1,1,6))
blocks.place(BEDROCK, pos(-2,1,6))
blocks.place(BEDROCK, pos(-3,1,6))
blocks.place(BEDROCK, pos(-4,1,6))
blocks.place(BEDROCK, pos(-5,1,6))
blocks.place(BEDROCK, pos(-0,1,6))
//wall2 2
blocks.place(BEDROCK,  pos(-1,2,6))
blocks.place(BEDROCK, pos(-2,2,6))
blocks.place(BEDROCK, pos(-3,2,6))
blocks.place(BEDROCK, pos(-4,2,6))
blocks.place(BEDROCK, pos(-5,2,6))
blocks.place(BEDROCK, pos(-0,2,6))
//wall2 3
blocks.place(BEDROCK,  pos(-1,3,6))
blocks.place(BEDROCK, pos(-2,3,6))
blocks.place(BEDROCK, pos(-3,3,6))
blocks.place(BEDROCK, pos(-4,3,6))
blocks.place(BEDROCK, pos(-5,3,6))
blocks.place(BEDROCK, pos(-0,3,6))

blocks.place(BEDROCK,  pos(-1,4,6))
blocks.place(BEDROCK, pos(-2,4,6))
blocks.place(BEDROCK, pos(-3,4,6))
blocks.place(BEDROCK, pos(-4,4,6))
blocks.place(BEDROCK, pos(-5,4,6))
blocks.place(BEDROCK, pos(-0,4,6))

blocks.place(BEDROCK,  pos(-1,5,6))
blocks.place(BEDROCK, pos(-2,5,6))
blocks.place(BEDROCK, pos(-3,5,6))
blocks.place(BEDROCK, pos(-4,5,6))
blocks.place(BEDROCK, pos(-5,5,6))
blocks.place(BEDROCK, pos(-0,5,6))
//wall lenght wall

blocks.place(BEDROCK, pos(-0,4,4))
blocks.place(BEDROCK, pos(-0,3,4))
blocks.place(BEDROCK, pos(-0,2,4))
blocks.place(BEDROCK, pos(-0,1,4))

blocks.place(BEDROCK, pos(-0,4,3))
blocks.place(BEDROCK, pos(-0,3,3))
blocks.place(BEDROCK, pos(-0,2,3))
blocks.place(BEDROCK, pos(-0,1,3))


blocks.place(BEDROCK, pos(-0,4,2))
blocks.place(BEDROCK, pos(-0,3,2))
blocks.place(BEDROCK, pos(-0,2,2))
blocks.place(BEDROCK, pos(-0,1,2))

blocks.place(BEDROCK, pos(-0,4,1))
blocks.place(BEDROCK, pos(-0,3,1))
blocks.place(BEDROCK, pos(-0,2,1))
blocks.place(BEDROCK, pos(-0,1,1))
blocks.place(BEDROCK, pos(-0,0,1))

blocks.place(BEDROCK, pos(-0,4,6))
blocks.place(BEDROCK, pos(-0,3,6))
blocks.place(BEDROCK, pos(-0,2,6))
blocks.place(BEDROCK, pos(-0,1,6))
blocks.place(BEDROCK, pos(-0,0,6))
